name: Incurably Curious
favicon: null
layout_spectrum: 0.3694302679505199
typography_spectrum: 0.6067292694933712
title: Incurably Curious
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.26270548324100673
  lightness: 0.5634005581960082
  saturation: 0.17910948349162936
  rhythmicContrast: 0.46622302662581205
purpose: []
